<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="style.css">
	<title>Bon de commande</title>
</head>
<body>

        <h1>Bons de commande</h1>

        <table class="standard-table">
            <caption>Liste des commandes</caption>
            <thead>
           
            
                <tr>
                    <th>Commande</th>
                    <th>Date de la commande</th>
                    <th>Date de livraison</th>
                    <th>Statut</th>
                </tr>
            </thead>
            <tbody>

            <?php foreach($bd as $value) :?>
                     <tr>
                        <td>
                            <a href="order-form.php?orderNumber=<?php echo $value['orderNumber']?>"><?php echo $value['orderNumber']?></a>
                        </td>
                        <td><?php echo $value['orderDate']?></td>
                        <td><?php echo $value['shippedDate']?></td>
                        <td><?php echo $value['status']?></td>
                    </tr>
                <?php endforeach; ?>
                                    
             </tbody>
        </table>
    


</body>
</html>

               