<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
	<title>Order-form</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

        <h1>Bons de commande</h1>

        <a href="index.php">Retourner à l'accueil</a>

        <!-- Etiquette avec fiche client -->
        <article class="order-form-customer">
            <h2><?= $result['customerName'] ?></h2>
            <h3><?= $result['contactFirstName']?> <?= $result['contactLastName']?></h3>
            <p><?= $result['addressLine1'] ?></p>
            <p></p>
            <p><?= $result['postalCode'] ?> <?= $result['city'] ?></p>
        </article>
        <hr>

        <!-- Le bon de commande -->
        <table class="standard-table">
            <caption>Bon de commande n°<?= $numorder ?></caption>
            <thead>
                <tr>
                    <th>Produit</th>
                    <th class="money-column">Prix Unitaire</th>
                    <th>Quantité</th>
                    <th class="money-column">Prix Total</th>
                </tr>
            </thead>
            <!-- Un footer de tableau HTML se positionne AVANT le body ! -->
            <tfoot>
               
                <tr>
                    <th colspan="3">Montant Total : HT</th>
                    <th><?= number_format($ht['prixtot'],2,',',' ') ?>  Prix Ht</th>
                </tr>
                <tr>
                    <th colspan="3">TVA (20 %) </th>
                    <th><?= number_format($ht['prixtot']*0.2,2,',',' ') ?>  Montant Tva calculée</th>
                </tr>
                <tr>
                    <th colspan="3">Montant Total TTC </th>
                    <!-- Multiplier par 1.20 revient à ajouter 20% à une variable -->
                    <th><?= number_format($ht['prixtot']*1.2 ,2,',',' ')?>  Montant TTC</th>
                </tr>
            </tfoot>
           <tbody>
               <?php foreach ($orderLine as $value):?>
                    <tr>
                        <td><?= $value['productName'] ?></td>
                        <td class="money-column"><?= $value['priceEach'] ?></td> 
                        <td ><?= $value['quantityOrdered'] ?></td>               
                        <td class="money-column"><?= number_format($value['tot'],2,',',' ') ?></td>               
                        
                    </tr>
                <?php endforeach ?> 



           </tbody>
        </table>
    
</body>
</html>